### ISSUE TITLE
 "serial_number": "<your-arduino-random-uuid>",

### ISSUE THREAD

**Issue by davidrib** [muzzley/yun-muzzley-lock#2]
were I get :
"serial_number": "<your-arduino-random-uuid>",
(fom  yun-muzzley-lock/muzzley.json.conf)

It still not working
Ciao works now
MCU<0;no_messagemuzzley;r>MPU

I can add the lock from my network, but still not working

Thanks
David Ribeiro

**Comment by jorgeclaro** [comment]
That serial_number can be any string that you would like. You just have to choose it, before register your Arduino to the Muzzley cloud. Now, just delete the device_key.key if you want to change it (and remember to delete the tile that you already added on your phone).

It is useful to add your devices to your Muzzley user account if you prefer to use that, instead of UPNP discovery. It is targeted for more simpler projects that may run on less powerful hardware devices like micro-controllers. You can try it, if you change that option on your app definition.

If you could find your device on your local network, that means the the muzzley connector is working properly. Check the **/log/muzzley.log** for messages received from the muzzley core, when you press the open button on the widget interface (I am assuming that you already created the widget interface with the sample code, and choose it on the app definition. If not, I can help with that).

At this point if the **components** and **properties** names **match**, the pin 13 should turn on the red LED on the board for a brief instant. Edit the sketch for a larger interval if you preffer.

The **/log/ciao.log** can be helpful, but it will be constantly receiving read messages from the MCU to the Ciao server and may be a little hard to read anything, as you may have noticed. Lastly, you may want to take a look at the MCU serial log, since it will only show the useful messages received from the Ciao server.

**Comment by davidrib** [comment]
It Works now Thanks for the help,
How do I delete the tile that  I before added on my phone?, I now have 2 switches, it happen after I format my arduino yun!
I'm already created the widget interface with the sample code but how can I chose it on app defitition?

David Ribeiro

**Comment by jorgeclaro** [comment]
To choose the widget interface, open your app detention and select the name of your widget on the **Interface UUID** field.

To delete the tile, just tap on it, to open the widget interface. Then at the top right corner, tap on the edit button with the pencil icon. In this screen you can edit the name of the tile, or delete it with the **Delete Device** button at the bottom.

Jorge Claro
